name: firstflut
description: Team Application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.0
  cloud_firestore: ^0.9.5
  firebase_auth: ^0.8.1
  datetime_picker_formfield: ^0.1.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  intl: ^0.15.7
  scoped_model: ^1.0.1
  frideos: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icons/volleyball_serve.png
  image_path_ios: assets/icons/volleyball_serve.png
 
flutter:

  uses-material-design: true

  assets:
    - assets/
 
